### PR TITLE
[pmp] Remove MSECCFG reads from trap handler when Smepmp is disabled

### PR DESCRIPTION
**Pull request by marnovandermaas**
Proposed fix for the following comment: https://github.com/chipsalliance/riscv-dv/commit/31a73ff26a0cd26dd3033ae29fa3df0aa9d28b64#r94906388
@JJ-Gaisler

### CODE REVIEW

**Comment by marnovandermaas** [comment]
@hcallahan-lowrisc, @GregAC would you mind having a look?

**Comment by GregAC** [comment]
LGTM thanks @marnovandermaas @kgugala would you mind merging this?

**Review by kgugala — APPROVED** [review]

**Comment by kgugala** [comment]
merged, thanks!

**Comment by Aswinofficial-code** [comment]
@kgugala sir how this line is appearing in .s file ( csrrsi       a7, 0x3b7, 20) which uses pmpaddr 7 even if i set this bit support_pmp = 0; to zero

**Comment by marnovandermaas** [comment]
@Aswinofficial-code this fix was meant to handle the case where support_pmp = 1 and support_epmp = 0. It doesn't change the behaviour of support_pmp = 0

**Pull request merged**
